---
title: Justin Charles
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title_after: |
  Designer & Developer
description: |
  Designer and developer living in Brooklyn, New York.
author: Justin Charles
encoding: utf-8
language: en-us
source: "./source"
destination: "./build"
baseurl: ''
url: http://127.0.0.1.xip.io:9999
root: "/"
permalink: "/:categories/:title/"
markdown: kramdown
future: true
show_drafts: true
limit_posts: 5
favicons: true
openGraph: true
twitterCards:
  username: justincharles
analytics:
  id: UA-XXXXXX-XX
  domain: http://justincharl.es
exclude:
- vendor
